In [10]:
import numpy as np

## Create a 3x3 matrix in numpy and python

In [2]:
array = np.random.rand(3, 3)
array

array([[0.10905946, 0.20446297, 0.07565436],
       [0.30925192, 0.55468764, 0.92166325],
       [0.14139816, 0.11002996, 0.85941352]])

In [4]:
plist = array.tolist()
plist

[[0.10905945827930352, 0.20446297331111907, 0.07565436119423774],
 [0.3092519157625301, 0.554687640317682, 0.9216632497378383],
 [0.14139816095913582, 0.11002996141122012, 0.8594135244462626]]

Speed of just numpy

In [25]:
large_array = np.random.rand(10000, 10000)
large_list = large_array.tolist()

In [26]:
%%timeit 
large_array.mean()

110 ms ± 1.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Python doesn't have a `mean` function natively, so we use numpy to compute. 

Speed of numpy applied to list. 

In [27]:
%%timeit 
np.mean(large_list)

4.62 s ± 56.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**Quite the difference.**

# Slicing

In [15]:
array[:2, :2]

array([[0.10905946, 0.20446297],
       [0.30925192, 0.55468764]])

In [20]:
[x[:2] for x in plist[:2]]

[[0.10905945827930352, 0.20446297331111907],
 [0.3092519157625301, 0.554687640317682]]

# Multiplication

In [17]:
array * 100

array([[10.90594583, 20.44629733,  7.56543612],
       [30.92519158, 55.46876403, 92.16632497],
       [14.1398161 , 11.00299614, 85.94135244]])

In [19]:
[[x*100 for x in y] for y in plist]

[[10.905945827930353, 20.446297331111907, 7.565436119423774],
 [30.92519157625301, 55.4687640317682, 92.16632497378383],
 [14.139816095913583, 11.002996141122011, 85.94135244462626]]

# Powers

In [18]:
array ** 2

array([[0.01189397, 0.04180511, 0.00572358],
       [0.09563675, 0.30767838, 0.84946315],
       [0.01999344, 0.01210659, 0.73859161]])

In [21]:
[[x**2 for x in y] for y in plist]

[[0.011893965440175146, 0.04180510745522339, 0.005723582367708186],
 [0.095636747402795, 0.3076783783211982, 0.8494631459173129],
 [0.019993439922625682, 0.01210659240815459, 0.7385916060011468]]

# Matrix Multiplication

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Matrix_multiplication_qtl1.svg/1200px-Matrix_multiplication_qtl1.svg.png" style="width:600px"/>

In [22]:
another_array = np.random.rand(3, 3)
array@another_array

array([[0.20105404, 0.20227289, 0.27110543],
       [0.65831001, 0.90711271, 0.86786145],
       [0.29515952, 0.55187604, 0.33265549]])

**Basically impossible in native python.**

## NumPy is elegant and easy. Python not really so much. 